name: Workflow de joshalval - Gestión de Issues
on:
  workflow_dispatch:
  issues:
    types: [opened, edited, labeled]
  project_card:
    types: [moved]

jobs:
  gestion-automatica:
    runs-on: ubuntu-latest
    steps:
      - name: Bienvenida al Issue
        if: github.event_name == 'issues'
        run: echo "Se ha detectado actividad en el Issue #${{ github.event.issue.number }}"

      - name: Añadir etiqueta automática
        if: github.event.action == 'opened'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "pendiente-revision"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Log de Auditoría
        run: |
          echo "Usuario: ${{ github.actor }}"
          echo "Evento: ${{ github.event_name }}"
